version: '3.7'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile-dev
        working_dir: /htdocs
        ports:
            - "4000:80"
        volumes:
            - ./src/:/htdocs/
