index:
    path: /
    controller: App\Controller\DefaultController::indexAction

tasks:
    path: /tasks
    controller: App\Controller\TasksController::indexAction
    methods: [GET]

task_add:
    path: /task
    controller: App\Controller\TasksController::addAction
    methods: [POST,OPTIONS]

task_edit:
    path: /task/{id}
    controller: App\Controller\TasksController::updateAction
    requirements:
        id: \d+
    methods: [POST,OPTIONS]

task_delete:
    path: /task/delete/{id}
    controller: App\Controller\TasksController::deleteAction
    requirements:
        id: \d+
    methods: [POST,OPTIONS]
